# Generated by Django 4.2.10 on 2024-03-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertagpreference_user_id_utp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='recipe_id_usf',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user_id_usf',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertagpreference',
            old_name='tag_id_utp',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='usertagpreference',
            old_name='user_id_utp',
            new_name='user',
        ),
    ]
