# Generated by Django 4.2.10 on 2024-03-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user_id_men',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='menurecipe',
            old_name='menu_id_mnr',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='menurecipe',
            old_name='recipe_id_mnr',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='menurecipequeue',
            old_name='recipe_id_mrq',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='menurecipequeue',
            old_name='user_id_mrq',
            new_name='user_id',
        ),
    ]
