# Generated by Django 4.2.10 on 2024-03-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_rename_user_id_men_menu_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='menurecipe',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menurecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='menurecipequeue',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='menurecipequeue',
            old_name='user_id',
            new_name='user',
        ),
    ]
