# Generated by Django 4.2.10 on 2024-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipestep_recipe_alter_recipestep_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientQuantity',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='ingredient_id_rpi',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='recipe_id_rpi',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='unit_measure_id_rpi',
            new_name='unit_measure',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id_rec',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientQuantity', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
