# Generated by Django 4.2.10 on 2024-02-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_recipeingredient_ingredientquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='order',
        ),
    ]
