# Generated by Django 5.0.2 on 2024-02-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipestep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
    ]
