# Generated by Django 4.2.10 on 2024-03-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_user_alter_recipestep_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipestep',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='recipestep',
            old_name='step',
            new_name='recipe_step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='recipes.recipestep'),
        ),
    ]
