# Generated by Django 4.2.10 on 2024-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_recipe_recipestep_recipe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/recipe_images'),
        ),
    ]
